### ISSUE TITLE
Support for El Capitan?

### ISSUE THREAD

**Issue by akaralar** [velyan/Mark#4]
I downloaded the latest release and I get the error  

```
You have OS X 10.11.6. The application requires OS X 10.12 or later.
```

Is there an El Capitan compatible release?

**Comment by velyan** [comment]
Thanks for reporting this!

This should be fixed in the latest release - https://github.com/velyan/Mark/releases/download/v1.1.1/Mark.zip.

**Comment by akaralar** [comment]
yeah downloaded it but still doesn't show up in extensions, and crashes when I click anything in the Mark.app

**Comment by akaralar** [comment]
Actually none of the extensions I installed show up in extensions, maybe xcode source editor section is only available in Sierra? 

I use these and they work ok without problems, but they don't show up in extensions either: 
https://github.com/Bouke/SwiftInitializerGenerator
https://github.com/markohlebar/Import
https://github.com/BalestraPatrick/CleanClosureXcode
https://github.com/mattgallagher/CwlWhitespace
